import { trpc } from '@/utils/trpc'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(["hello", { text: 'teste' }])
  if (isLoading) return <div>Loading...</div>
  if (data) return <div>{data.greeting}</div>
  return (
    <div className="h-screen w-screen flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-7xl">
        vazio
      </main>

    </div>
  )
}

export default Home
