import { trpc } from '@/utils/trpc'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = (props) => {
  return (
    <div className="h-screen w-screen flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-7xl">
        Feature ainda não implementada.
      </main>

    </div>
  )
}

export default Home
